actor_lr: 0.001
agent_seed: 1988
clip_grads: True
clip_rho: False
cov: 0.1
critic_lr: 0.01
env_seed: 1996
episode_length: 100
gamma: 0.99
lambda_pi: 0.1
lambda_v: 0.9
max_reward: 4
min_reward: 0
model: maopac
num_actions: 2
num_agents: 10
num_episodes: 1
num_state_features: 10
num_states: 20
num_trains: 1000
policy_units: 64
results_path: results

decreasing_stepsizes: True
actor_stepsize_exponent: 0.9
critic_stepsize_exponent: 0.8

edge_probability: 0.3

save_results: True

multistep_consensus_steps: 0
rho_consensus: perfect